# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zayavka_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('zayavka_text', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'zayavka',
            },
        ),
    ]
